{"variants":[{"paths":["\/documentation\/coreuikit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coreuikit"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionViewCell","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableViewCell"]},{"title":"Protocols","identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseInitializableView","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseView","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseViewModel"]},{"title":"Enumerations","identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/ConstraintRelation"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"CoreUIKit","title":"CoreUIKit","symbolKind":"module","role":"collection","modules":[{"name":"CoreUIKit"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.example.CoreUIKit/documentation/CoreUIKit":{"role":"collection","title":"CoreUIKit","abstract":[],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/CoreUIKitVersionNumber":{"role":"symbol","title":"CoreUIKitVersionNumber","fragments":[{"kind":"identifier","text":"CoreUIKitVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for CoreUIKit."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/CoreUIKitVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit\/coreuikitversionnumber"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableView":{"role":"symbol","title":"BaseTableView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableView"}],"abstract":[{"type":"text","text":"A view replacing direct use of "},{"type":"codeVoice","code":"UITableView"},{"type":"text","text":" with added features."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseTableView"}],"url":"\/documentation\/coreuikit\/basetableview"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableViewCell":{"role":"symbol","title":"BaseTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableViewCell"}],"abstract":[{"type":"text","text":"Provides core features for "},{"type":"codeVoice","code":"UITableViewCell"},{"type":"text","text":" with data model and setups"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseTableViewCell"}],"url":"\/documentation\/coreuikit\/basetableviewcell"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseViewModel":{"role":"symbol","title":"BaseViewModel","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewModel"}],"abstract":[{"type":"text","text":"Data model used by view for it’s presentation"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewModel"}],"url":"\/documentation\/coreuikit\/baseviewmodel"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable":{"role":"symbol","title":"Anchorable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Anchorable"}],"abstract":[],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Anchorable"}],"url":"\/documentation\/coreuikit\/anchorable"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseInitializableView":{"role":"symbol","title":"BaseInitializableView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseInitializableView"}],"abstract":[{"type":"text","text":"A view that can be initialized with a data model"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseInitializableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseInitializableView"}],"url":"\/documentation\/coreuikit\/baseinitializableview"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/ConstraintRelation":{"role":"symbol","title":"ConstraintRelation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConstraintRelation"}],"abstract":[{"type":"text","text":"Core relation type between any two constraints"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/ConstraintRelation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConstraintRelation"}],"url":"\/documentation\/coreuikit\/constraintrelation"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseCollectionViewCell":{"role":"symbol","title":"BaseCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollectionViewCell"}],"abstract":[{"type":"text","text":"Provides core features for "},{"type":"codeVoice","code":"UICollectionViewCell"},{"type":"text","text":" with data model and setups"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseCollectionViewCell"}],"url":"\/documentation\/coreuikit\/basecollectionviewcell"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseView":{"role":"symbol","title":"BaseView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseView"}],"abstract":[{"type":"text","text":"Abstract representation of any view that provides data driven setups"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseView"}],"url":"\/documentation\/coreuikit\/baseview"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseCollectionView":{"role":"symbol","title":"BaseCollectionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollectionView"}],"abstract":[{"type":"text","text":"A view replacing direct use of "},{"type":"codeVoice","code":"UICollectionView"},{"type":"text","text":" with added features."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseCollectionView"}],"url":"\/documentation\/coreuikit\/basecollectionview"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/CoreUIKitVersionString":{"role":"symbol","title":"CoreUIKitVersionString","fragments":[{"kind":"identifier","text":"CoreUIKitVersionString"}],"abstract":[{"type":"text","text":"Project version string for CoreUIKit."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/CoreUIKitVersionString","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit\/coreuikitversionstring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView"]},{"title":"Variables","identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/CoreUIKitVersionNumber","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/CoreUIKitVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseTableView\/title","value":"BaseTableView"},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseTableView\/fragments","value":[{"kind":"identifier","text":"BaseTableView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseCollectionView\/title","value":"BaseCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseCollectionView\/fragments","value":[{"kind":"identifier","text":"BaseCollectionView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}