{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Anchorable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorPluggable","preciseIdentifier":"s:9CoreUIKit15AnchorPluggableP","text":"AnchorPluggable"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable","preciseIdentifier":"s:9CoreUIKit16AnchorProvidableP","text":"AnchorProvidable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coreuikit\/anchorable"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorPluggable","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionViewCell","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableViewCell"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provides useful features for anything that supports adding constraints to itself."},{"type":"text","text":" "},{"type":"text","text":"Best usecases are Views and Guides."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Anchorable"}],"title":"Anchorable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:9CoreUIKit10AnchorableP","modules":[{"name":"CoreUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"Anchorable"}]},"hierarchy":{"paths":[["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/add(to:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/allAnchorsSame(on:margin:)-2bbh","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/bottom(with:relation:margin:)-391n4","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/center(on:with:)-6lqcj","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/centerX(with:margin:)-4am6u","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/centerY(with:margin:)-2ygyi","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/height(value:relation:)-4lctc","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/leading(with:relation:margin:)-6pg1","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/set(identifier:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/setConstraintIdentifier(for:for:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/top(with:relation:margin:)-84vte","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/trailing(with:relation:margin:)-8bksz","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/width(value:relation:)-2cglj","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/with(width:height:)-2md8r"]}],"references":{"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/set(identifier:)":{"role":"symbol","title":"set(identifier:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets "},{"type":"codeVoice","code":"accessibilityIdentifier"},{"type":"text","text":" on current view"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/set(identifier:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/set(identifier:)"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableViewCell":{"role":"symbol","title":"BaseTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableViewCell"}],"abstract":[{"type":"text","text":"Provides core features for "},{"type":"codeVoice","code":"UITableViewCell"},{"type":"text","text":" with data model and setups"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseTableViewCell"}],"url":"\/documentation\/coreuikit\/basetableviewcell"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/centerX(with:margin:)-4am6u":{"defaultImplementations":1,"role":"symbol","title":"centerX(with:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"centerX"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutXAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutXAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets centerX anchor of the current view to provided anchor"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/centerX(with:margin:)-4am6u","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/centerx(with:margin:)-4am6u"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/height(value:relation:)-4lctc":{"defaultImplementations":1,"role":"symbol","title":"height(value:relation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"relation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConstraintRelation","preciseIdentifier":"s:9CoreUIKit18ConstraintRelationO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets height anchor for the current view to provided value and relation"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/height(value:relation:)-4lctc","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/height(value:relation:)-4lctc"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/bottom(with:relation:margin:)-391n4":{"defaultImplementations":1,"role":"symbol","title":"bottom(with:relation:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutYAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"relation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConstraintRelation","preciseIdentifier":"s:9CoreUIKit18ConstraintRelationO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets bottom anchor of the current view to provided anchor"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/bottom(with:relation:margin:)-391n4","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/bottom(with:relation:margin:)-391n4"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable":{"role":"symbol","title":"Anchorable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Anchorable"}],"abstract":[{"type":"text","text":"Provides useful features for anything that supports adding constraints to itself."},{"type":"text","text":" "},{"type":"text","text":"Best usecases are Views and Guides."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Anchorable"}],"url":"\/documentation\/coreuikit\/anchorable"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/trailing(with:relation:margin:)-8bksz":{"defaultImplementations":1,"role":"symbol","title":"trailing(with:relation:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trailing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutXAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutXAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"relation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConstraintRelation","preciseIdentifier":"s:9CoreUIKit18ConstraintRelationO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets trailing anchor of the current view to provided anchor"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/trailing(with:relation:margin:)-8bksz","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/trailing(with:relation:margin:)-8bksz"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/with(width:height:)-2md8r":{"defaultImplementations":1,"role":"symbol","title":"with(width:height:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"with"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets width and heoght anchor with given value on current view"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/with(width:height:)-2md8r","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/with(width:height:)-2md8r"},"doc://com.example.CoreUIKit/documentation/CoreUIKit":{"role":"collection","title":"CoreUIKit","abstract":[{"type":"text","text":"Less learning, Less code!"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/center(on:with:)-6lqcj":{"defaultImplementations":1,"role":"symbol","title":"center(on:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"center"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets center (X & Y) anchor of the current view to provided anchor"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/center(on:with:)-6lqcj","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/center(on:with:)-6lqcj"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/setConstraintIdentifier(for:for:)":{"role":"symbol","title":"setConstraintIdentifier(for:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConstraintIdentifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets identifier for given constraints"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/setConstraintIdentifier(for:for:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/setconstraintidentifier(for:for:)"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/width(value:relation:)-2cglj":{"defaultImplementations":1,"role":"symbol","title":"width(value:relation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"relation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConstraintRelation","preciseIdentifier":"s:9CoreUIKit18ConstraintRelationO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets width anchor for the current view to provided value and relation"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/width(value:relation:)-2cglj","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/width(value:relation:)-2cglj"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/top(with:relation:margin:)-84vte":{"defaultImplementations":1,"role":"symbol","title":"top(with:relation:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutYAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"relation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConstraintRelation","preciseIdentifier":"s:9CoreUIKit18ConstraintRelationO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets top anchor of the current view to provided anchor"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/top(with:relation:margin:)-84vte","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/top(with:relation:margin:)-84vte"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/leading(with:relation:margin:)-6pg1":{"defaultImplementations":1,"role":"symbol","title":"leading(with:relation:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leading"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutXAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutXAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"relation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConstraintRelation","preciseIdentifier":"s:9CoreUIKit18ConstraintRelationO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets leading anchor of the current view to provided anchor"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/leading(with:relation:margin:)-6pg1","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/leading(with:relation:margin:)-6pg1"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/allAnchorsSame(on:margin:)-2bbh":{"defaultImplementations":1,"role":"symbol","title":"allAnchorsSame(on:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allAnchorsSame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets leading, trailing, top and bottom anchors equal to parent view’s anchors"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/allAnchorsSame(on:margin:)-2bbh","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/allanchorssame(on:margin:)-2bbh"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/centerY(with:margin:)-2ygyi":{"defaultImplementations":1,"role":"symbol","title":"centerY(with:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"centerY"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutYAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets centerY anchor of the current view to provided anchor"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/centerY(with:margin:)-2ygyi","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/centery(with:margin:)-2ygyi"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorProvidable":{"role":"symbol","title":"AnchorProvidable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnchorProvidable"}],"abstract":[{"type":"text","text":"An object that can provide link\/access to anchors\/constraints"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnchorProvidable"}],"url":"\/documentation\/coreuikit\/anchorprovidable"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable/add(to:)":{"role":"symbol","title":"add(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Adds current view to provided parent view (if it’s not already added)"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable\/add(to:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorable\/add(to:)"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorPluggable":{"role":"symbol","title":"AnchorPluggable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnchorPluggable"}],"abstract":[{"type":"text","text":"A mechanism to plug a given view into any other using relative anchors and margins"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorPluggable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnchorPluggable"}],"url":"\/documentation\/coreuikit\/anchorpluggable"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseCollectionView":{"role":"symbol","title":"BaseCollectionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollectionView"}],"abstract":[{"type":"text","text":"A view replacing direct use of "},{"type":"codeVoice","code":"UICollectionView"},{"type":"text","text":" with added features."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseCollectionView"}],"url":"\/documentation\/coreuikit\/basecollectionview"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseCollectionViewCell":{"role":"symbol","title":"BaseCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollectionViewCell"}],"abstract":[{"type":"text","text":"Provides core features for "},{"type":"codeVoice","code":"UICollectionViewCell"},{"type":"text","text":" with data model and setups"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseCollectionViewCell"}],"url":"\/documentation\/coreuikit\/basecollectionviewcell"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableView":{"role":"symbol","title":"BaseTableView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableView"}],"abstract":[{"type":"text","text":"A view replacing direct use of "},{"type":"codeVoice","code":"UITableView"},{"type":"text","text":" with added features."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseTableView"}],"url":"\/documentation\/coreuikit\/basetableview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseCollectionView\/title","value":"BaseCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseCollectionView\/fragments","value":[{"kind":"identifier","text":"BaseCollectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseTableView\/title","value":"BaseTableView"},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseTableView\/fragments","value":[{"kind":"identifier","text":"BaseTableView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}