{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnchorProvidable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coreuikit\/anchorprovidable"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionViewCell","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableViewCell"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object that can provide link\/access to anchors\/constraints"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnchorProvidable"}],"title":"AnchorProvidable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:9CoreUIKit16AnchorProvidableP","modules":[{"name":"CoreUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"AnchorProvidable"}]},"hierarchy":{"paths":[["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getBottom(with:relation:margin:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getCenterX(with:margin:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getCenterY(with:margin:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getHeight(with:relation:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getLeading(with:relation:margin:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getTop(with:relation:margin:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getTrailing(with:relation:margin:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getWidth(with:relation:)"]}],"references":{"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseCollectionViewCell":{"role":"symbol","title":"BaseCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollectionViewCell"}],"abstract":[{"type":"text","text":"Provides core features for "},{"type":"codeVoice","code":"UICollectionViewCell"},{"type":"text","text":" with data model and setups"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseCollectionViewCell"}],"url":"\/documentation\/coreuikit\/basecollectionviewcell"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorProvidable/getTop(with:relation:margin:)":{"role":"symbol","title":"getTop(with:relation:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTop"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutYAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"relation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConstraintRelation","preciseIdentifier":"s:9CoreUIKit18ConstraintRelationO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"}],"abstract":[{"type":"text","text":"Creates top anchor with provided connecting anchor, relation and margin"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getTop(with:relation:margin:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorprovidable\/gettop(with:relation:margin:)"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorProvidable/getWidth(with:relation:)":{"role":"symbol","title":"getWidth(with:relation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getWidth"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"relation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConstraintRelation","preciseIdentifier":"s:9CoreUIKit18ConstraintRelationO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"}],"abstract":[{"type":"text","text":"Creates width anchor with provided relation and constant value"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getWidth(with:relation:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorprovidable\/getwidth(with:relation:)"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorProvidable/getTrailing(with:relation:margin:)":{"role":"symbol","title":"getTrailing(with:relation:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTrailing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutXAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutXAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"relation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConstraintRelation","preciseIdentifier":"s:9CoreUIKit18ConstraintRelationO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"}],"abstract":[{"type":"text","text":"Creates trailing anchor with provided connecting anchor, relation and margin"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getTrailing(with:relation:margin:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorprovidable\/gettrailing(with:relation:margin:)"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorProvidable/getBottom(with:relation:margin:)":{"role":"symbol","title":"getBottom(with:relation:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBottom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutYAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"relation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConstraintRelation","preciseIdentifier":"s:9CoreUIKit18ConstraintRelationO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"}],"abstract":[{"type":"text","text":"Creates bottom anchor with provided connecting anchor, relation and margin"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getBottom(with:relation:margin:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorprovidable\/getbottom(with:relation:margin:)"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorProvidable/getCenterY(with:margin:)":{"role":"symbol","title":"getCenterY(with:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCenterY"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutYAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"}],"abstract":[{"type":"text","text":"Creates center Y anchor with provided connecting anchor and margin"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getCenterY(with:margin:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorprovidable\/getcentery(with:margin:)"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorProvidable/getLeading(with:relation:margin:)":{"role":"symbol","title":"getLeading(with:relation:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLeading"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutXAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutXAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"relation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConstraintRelation","preciseIdentifier":"s:9CoreUIKit18ConstraintRelationO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"}],"abstract":[{"type":"text","text":"Creates leading anchor with provided connecting anchor, relation and margin"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getLeading(with:relation:margin:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorprovidable\/getleading(with:relation:margin:)"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableViewCell":{"role":"symbol","title":"BaseTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableViewCell"}],"abstract":[{"type":"text","text":"Provides core features for "},{"type":"codeVoice","code":"UITableViewCell"},{"type":"text","text":" with data model and setups"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseTableViewCell"}],"url":"\/documentation\/coreuikit\/basetableviewcell"},"doc://com.example.CoreUIKit/documentation/CoreUIKit":{"role":"collection","title":"CoreUIKit","abstract":[{"type":"text","text":"Less learning, Less code!"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorProvidable/getCenterX(with:margin:)":{"role":"symbol","title":"getCenterX(with:margin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCenterX"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutXAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutXAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"margin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"}],"abstract":[{"type":"text","text":"Creates center X anchor with provided connecting anchor and margin"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getCenterX(with:margin:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorprovidable\/getcenterx(with:margin:)"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseCollectionView":{"role":"symbol","title":"BaseCollectionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollectionView"}],"abstract":[{"type":"text","text":"A view replacing direct use of "},{"type":"codeVoice","code":"UICollectionView"},{"type":"text","text":" with added features."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseCollectionView"}],"url":"\/documentation\/coreuikit\/basecollectionview"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable":{"role":"symbol","title":"Anchorable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Anchorable"}],"abstract":[{"type":"text","text":"Provides useful features for anything that supports adding constraints to itself."},{"type":"text","text":" "},{"type":"text","text":"Best usecases are Views and Guides."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Anchorable"}],"url":"\/documentation\/coreuikit\/anchorable"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorProvidable/getHeight(with:relation:)":{"role":"symbol","title":"getHeight(with:relation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getHeight"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"relation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConstraintRelation","preciseIdentifier":"s:9CoreUIKit18ConstraintRelationO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"}],"abstract":[{"type":"text","text":"Creates height anchor with provided relation and constant value"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable\/getHeight(with:relation:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorprovidable\/getheight(with:relation:)"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableView":{"role":"symbol","title":"BaseTableView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableView"}],"abstract":[{"type":"text","text":"A view replacing direct use of "},{"type":"codeVoice","code":"UITableView"},{"type":"text","text":" with added features."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseTableView"}],"url":"\/documentation\/coreuikit\/basetableview"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorProvidable":{"role":"symbol","title":"AnchorProvidable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnchorProvidable"}],"abstract":[{"type":"text","text":"An object that can provide link\/access to anchors\/constraints"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnchorProvidable"}],"url":"\/documentation\/coreuikit\/anchorprovidable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseCollectionView\/title","value":"BaseCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseCollectionView\/fragments","value":[{"kind":"identifier","text":"BaseCollectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseTableView\/title","value":"BaseTableView"},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseTableView\/fragments","value":[{"kind":"identifier","text":"BaseTableView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}