{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnchorPluggable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coreuikit\/anchorpluggable"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionViewCell","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableViewCell"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorPluggable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A mechanism to plug a given view into any other using relative anchors and margins"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnchorPluggable"}],"title":"AnchorPluggable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:9CoreUIKit15AnchorPluggableP","modules":[{"name":"CoreUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"AnchorPluggable"}]},"hierarchy":{"paths":[["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorPluggable\/plug(to:having:)"]}],"references":{"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableViewCell":{"role":"symbol","title":"BaseTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableViewCell"}],"abstract":[{"type":"text","text":"Provides core features for "},{"type":"codeVoice","code":"UITableViewCell"},{"type":"text","text":" with data model and setups"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseTableViewCell"}],"url":"\/documentation\/coreuikit\/basetableviewcell"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorPluggable":{"role":"symbol","title":"AnchorPluggable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnchorPluggable"}],"abstract":[{"type":"text","text":"A mechanism to plug a given view into any other using relative anchors and margins"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorPluggable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnchorPluggable"}],"url":"\/documentation\/coreuikit\/anchorpluggable"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableView":{"role":"symbol","title":"BaseTableView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableView"}],"abstract":[{"type":"text","text":"A view replacing direct use of "},{"type":"codeVoice","code":"UITableView"},{"type":"text","text":" with added features."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseTableView"}],"url":"\/documentation\/coreuikit\/basetableview"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable":{"role":"symbol","title":"Anchorable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Anchorable"}],"abstract":[{"type":"text","text":"Provides useful features for anything that supports adding constraints to itself."},{"type":"text","text":" "},{"type":"text","text":"Best usecases are Views and Guides."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Anchorable"}],"url":"\/documentation\/coreuikit\/anchorable"},"doc://com.example.CoreUIKit/documentation/CoreUIKit":{"role":"collection","title":"CoreUIKit","abstract":[{"type":"text","text":"Less learning, Less code!"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseCollectionView":{"role":"symbol","title":"BaseCollectionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollectionView"}],"abstract":[{"type":"text","text":"A view replacing direct use of "},{"type":"codeVoice","code":"UICollectionView"},{"type":"text","text":" with added features."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseCollectionView"}],"url":"\/documentation\/coreuikit\/basecollectionview"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseCollectionViewCell":{"role":"symbol","title":"BaseCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollectionViewCell"}],"abstract":[{"type":"text","text":"Provides core features for "},{"type":"codeVoice","code":"UICollectionViewCell"},{"type":"text","text":" with data model and setups"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseCollectionViewCell"}],"url":"\/documentation\/coreuikit\/basecollectionviewcell"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorPluggable/plug(to:having:)":{"defaultImplementations":1,"role":"symbol","title":"plug(to:having:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"plug"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"having"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"RelatableAnchor","preciseIdentifier":"s:9CoreUIKit15RelatableAnchorO"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Plugs in the provided anchors with thier relation to the view"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorPluggable\/plug(to:having:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/coreuikit\/anchorpluggable\/plug(to:having:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseTableView\/title","value":"BaseTableView"},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseTableView\/fragments","value":[{"kind":"identifier","text":"BaseTableView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseCollectionView\/title","value":"BaseCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseCollectionView\/fragments","value":[{"kind":"identifier","text":"BaseCollectionView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}