{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coreuikit\/basetableview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coreuikit\/basetableview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.example.CoreUIKit\/objc(cs)UITableView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorPluggable","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable","doc:\/\/com.example.CoreUIKit\/objc(pl)NSCoding","doc:\/\/com.example.CoreUIKit\/objc(pl)NSObject","doc:\/\/com.example.CoreUIKit\/objc(pl)CALayerDelegate","doc:\/\/com.example.CoreUIKit\/s7CVarArgP","doc:\/\/com.example.CoreUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.example.CoreUIKit\/s23CustomStringConvertibleP","doc:\/\/com.example.CoreUIKit\/SQ","doc:\/\/com.example.CoreUIKit\/SH","doc:\/\/com.example.CoreUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.example.CoreUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.example.CoreUIKit\/objc(pl)UIAppearance","doc:\/\/com.example.CoreUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/com.example.CoreUIKit\/objc(pl)UICoordinateSpace","doc:\/\/com.example.CoreUIKit\/objc(pl)UIDataSourceTranslating","doc:\/\/com.example.CoreUIKit\/objc(pl)UIDynamicItem","doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusItem","doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusItemScrollableContainer","doc:\/\/com.example.CoreUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.example.CoreUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.example.CoreUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.example.CoreUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.example.CoreUIKit\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/com.example.CoreUIKit\/objc(pl)UITraitEnvironment","doc:\/\/com.example.CoreUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A view replacing direct use of "},{"type":"codeVoice","code":"UITableView"},{"type":"text","text":" with added features."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableView"}],"title":"BaseTableView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CoreUIKit@objc(cs)BaseTableView","modules":[{"name":"CoreUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"BaseTableView"}]},"hierarchy":{"paths":[["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView\/init(with:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView\/dequeue(_:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView\/dequeue(_:for:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView\/register(_:)"]}],"references":{"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableView/register(_:)":{"role":"symbol","title":"register(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"CellType"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"CellType","preciseIdentifier":"s:9CoreUIKit13BaseTableViewC8registeryyxmSo07UITableE4CellCRbzlF0H4TypeL_xmfp"},{"kind":"text","text":".Type)"}],"abstract":[{"type":"text","text":"Registeres provided cell type with current "},{"type":"codeVoice","code":"BaseTableView"},{"type":"text","text":" instance"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView\/register(_:)","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit\/basetableview\/register(_:)"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableView":{"role":"symbol","title":"BaseTableView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableView"}],"abstract":[{"type":"text","text":"A view replacing direct use of "},{"type":"codeVoice","code":"UITableView"},{"type":"text","text":" with added features."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseTableView"}],"url":"\/documentation\/coreuikit\/basetableview"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableView/dequeue(_:)":{"role":"symbol","title":"dequeue(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dequeue"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"CellType"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"CellType","preciseIdentifier":"s:9CoreUIKit13BaseTableViewC7dequeueyxSgxmSo07UITableE4CellCRbzlF0H4TypeL_xmfp"},{"kind":"text","text":".Type) -> "},{"kind":"typeIdentifier","text":"CellType","preciseIdentifier":"s:9CoreUIKit13BaseTableViewC7dequeueyxSgxmSo07UITableE4CellCRbzlF0H4TypeL_xmfp"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Dequeues reusable registered cell type"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView\/dequeue(_:)","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit\/basetableview\/dequeue(_:)"},"doc://com.example.CoreUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.example.CoreUIKit\/SQ"},"doc://com.example.CoreUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.example.CoreUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UITraitEnvironment"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorPluggable":{"role":"symbol","title":"AnchorPluggable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnchorPluggable"}],"abstract":[{"type":"text","text":"A mechanism to plug a given view into any other using relative anchors and margins"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorPluggable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnchorPluggable"}],"url":"\/documentation\/coreuikit\/anchorpluggable"},"doc://com.example.CoreUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIDynamicItem"},"doc://com.example.CoreUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.example.CoreUIKit\/s7CVarArgP"},"doc://com.example.CoreUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIAppearance"},"doc://com.example.CoreUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIAppearanceContainer"},"doc://com.example.CoreUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://com.example.CoreUIKit/objc(pl)UIFocusItemScrollableContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemScrollableContainer","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusItemScrollableContainer"},"doc://com.example.CoreUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UICoordinateSpace"},"doc://com.example.CoreUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusItem"},"doc://com.example.CoreUIKit/objc(pl)UIDataSourceTranslating":{"type":"unresolvable","title":"UIKit.UIDataSourceTranslating","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIDataSourceTranslating"},"doc://com.example.CoreUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://com.example.CoreUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)CALayerDelegate"},"doc://com.example.CoreUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)NSCoding"},"doc://com.example.CoreUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.example.CoreUIKit\/s23CustomStringConvertibleP"},"doc://com.example.CoreUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIUserActivityRestoring"},"doc://com.example.CoreUIKit/documentation/CoreUIKit":{"role":"collection","title":"CoreUIKit","abstract":[{"type":"text","text":"Less learning, Less code!"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit"},"doc://com.example.CoreUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.example.CoreUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)NSObject"},"doc://com.example.CoreUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UILargeContentViewerItem"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableView/dequeue(_:for:)":{"role":"symbol","title":"dequeue(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dequeue"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"CellType"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"CellType","preciseIdentifier":"s:9CoreUIKit13BaseTableViewC7dequeue_3forxSgxm_10Foundation9IndexPathVtSo07UITableE4CellCRbzlF0L4TypeL_xmfp"},{"kind":"text","text":".Type, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CellType","preciseIdentifier":"s:9CoreUIKit13BaseTableViewC7dequeue_3forxSgxm_10Foundation9IndexPathVtSo07UITableE4CellCRbzlF0L4TypeL_xmfp"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Dequeues reusable registered cell type"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView\/dequeue(_:for:)","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit\/basetableview\/dequeue(_:for:)"},"doc://com.example.CoreUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.example.CoreUIKit\/SH"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable":{"role":"symbol","title":"Anchorable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Anchorable"}],"abstract":[{"type":"text","text":"Provides useful features for anything that supports adding constraints to itself."},{"type":"text","text":" "},{"type":"text","text":"Best usecases are Views and Guides."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Anchorable"}],"url":"\/documentation\/coreuikit\/anchorable"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseTableView/init(with:)":{"role":"symbol","title":"init(with:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Inits "},{"type":"codeVoice","code":"BaseTableView"},{"type":"text","text":" with provided parameters."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseTableView\/init(with:)","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit\/basetableview\/init(with:)"},"doc://com.example.CoreUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusItemContainer"},"doc://com.example.CoreUIKit/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","title":"UIKit.UISpringLoadedInteractionSupporting","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UISpringLoadedInteractionSupporting"},"doc://com.example.CoreUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.example.CoreUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.example.CoreUIKit\/s28CustomDebugStringConvertibleP"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/AnchorProvidable":{"role":"symbol","title":"AnchorProvidable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnchorProvidable"}],"abstract":[{"type":"text","text":"An object that can provide link\/access to anchors\/constraints"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/AnchorProvidable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnchorProvidable"}],"url":"\/documentation\/coreuikit\/anchorprovidable"},"doc://com.example.CoreUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusEnvironment"},"doc://com.example.CoreUIKit/objc(cs)UITableView":{"type":"unresolvable","title":"UITableView","identifier":"doc:\/\/com.example.CoreUIKit\/objc(cs)UITableView"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BaseTableView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BaseTableView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BaseTableView"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.example.CoreUIKit\/objc(cs)UITableView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseTableView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseTableView\/title","value":"BaseTableView"},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseTableView\/fragments","value":[{"kind":"identifier","text":"BaseTableView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}