{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollectionView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/coreuikit\/basecollectionview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/coreuikit\/basecollectionview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.example.CoreUIKit\/objc(cs)UICollectionView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable","doc:\/\/com.example.CoreUIKit\/objc(pl)NSCoding","doc:\/\/com.example.CoreUIKit\/objc(pl)NSObject","doc:\/\/com.example.CoreUIKit\/objc(pl)CALayerDelegate","doc:\/\/com.example.CoreUIKit\/s7CVarArgP","doc:\/\/com.example.CoreUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.example.CoreUIKit\/s23CustomStringConvertibleP","doc:\/\/com.example.CoreUIKit\/SQ","doc:\/\/com.example.CoreUIKit\/SH","doc:\/\/com.example.CoreUIKit\/s8SendableP","doc:\/\/com.example.CoreUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.example.CoreUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.example.CoreUIKit\/objc(pl)UIAppearance","doc:\/\/com.example.CoreUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/com.example.CoreUIKit\/objc(pl)UICoordinateSpace","doc:\/\/com.example.CoreUIKit\/objc(pl)UIDataSourceTranslating","doc:\/\/com.example.CoreUIKit\/objc(pl)UIDynamicItem","doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusItem","doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusItemScrollableContainer","doc:\/\/com.example.CoreUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.example.CoreUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.example.CoreUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.example.CoreUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.example.CoreUIKit\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/com.example.CoreUIKit\/objc(pl)UITraitEnvironment","doc:\/\/com.example.CoreUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A view replacing direct use of "},{"type":"codeVoice","code":"UICollectionView"},{"type":"text","text":" with added features."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollectionView"}],"title":"BaseCollectionView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CoreUIKit@objc(cs)BaseCollectionView","modules":[{"name":"CoreUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"BaseCollectionView"}]},"hierarchy":{"paths":[["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView\/init(with:layout:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView\/dequeue(_:for:)","doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView\/register(_:)"]}],"references":{"doc://com.example.CoreUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.example.CoreUIKit\/s8SendableP"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseCollectionView/init(with:layout:)":{"role":"symbol","title":"init(with:layout:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Inits "},{"type":"codeVoice","code":"BaseCollectionView"},{"type":"text","text":" with provided parameters."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView\/init(with:layout:)","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit\/basecollectionview\/init(with:layout:)"},"doc://com.example.CoreUIKit/objc(cs)UICollectionView":{"type":"unresolvable","title":"UICollectionView","identifier":"doc:\/\/com.example.CoreUIKit\/objc(cs)UICollectionView"},"doc://com.example.CoreUIKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)NSCoding"},"doc://com.example.CoreUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIUserActivityRestoring"},"doc://com.example.CoreUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusEnvironment"},"doc://com.example.CoreUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIDynamicItem"},"doc://com.example.CoreUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.example.CoreUIKit\/SH"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseCollectionView":{"role":"symbol","title":"BaseCollectionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollectionView"}],"abstract":[{"type":"text","text":"A view replacing direct use of "},{"type":"codeVoice","code":"UICollectionView"},{"type":"text","text":" with added features."}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseCollectionView"}],"url":"\/documentation\/coreuikit\/basecollectionview"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/Anchorable":{"role":"symbol","title":"Anchorable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Anchorable"}],"abstract":[],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/Anchorable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Anchorable"}],"url":"\/documentation\/coreuikit\/anchorable"},"doc://com.example.CoreUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusItem"},"doc://com.example.CoreUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.example.CoreUIKit\/s7CVarArgP"},"doc://com.example.CoreUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)NSObject"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseCollectionView/register(_:)":{"role":"symbol","title":"register(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"CellType"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"CellType","preciseIdentifier":"s:9CoreUIKit18BaseCollectionViewC8registeryyxmSo012UICollectionE4CellCRbzlF0H4TypeL_xmfp"},{"kind":"text","text":".Type)"}],"abstract":[{"type":"text","text":"Registeres provided cell type with current "},{"type":"codeVoice","code":"BaseCollectionView"},{"type":"text","text":" instance"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView\/register(_:)","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit\/basecollectionview\/register(_:)"},"doc://com.example.CoreUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.example.CoreUIKit\/SQ"},"doc://com.example.CoreUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.example.CoreUIKit\/s23CustomStringConvertibleP"},"doc://com.example.CoreUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)CALayerDelegate"},"doc://com.example.CoreUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusItemContainer"},"doc://com.example.CoreUIKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIAppearance"},"doc://com.example.CoreUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UITraitEnvironment"},"doc://com.example.CoreUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://com.example.CoreUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.example.CoreUIKit\/s28CustomDebugStringConvertibleP"},"doc://com.example.CoreUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.example.CoreUIKit/documentation/CoreUIKit":{"role":"collection","title":"CoreUIKit","abstract":[],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit"},"doc://com.example.CoreUIKit/objc(pl)UIFocusItemScrollableContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemScrollableContainer","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIFocusItemScrollableContainer"},"doc://com.example.CoreUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.example.CoreUIKit/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","title":"UIKit.UISpringLoadedInteractionSupporting","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UISpringLoadedInteractionSupporting"},"doc://com.example.CoreUIKit/objc(pl)UIDataSourceTranslating":{"type":"unresolvable","title":"UIKit.UIDataSourceTranslating","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIDataSourceTranslating"},"doc://com.example.CoreUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://com.example.CoreUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UILargeContentViewerItem"},"doc://com.example.CoreUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UICoordinateSpace"},"doc://com.example.CoreUIKit/documentation/CoreUIKit/BaseCollectionView/dequeue(_:for:)":{"role":"symbol","title":"dequeue(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dequeue"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"CellType"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"CellType","preciseIdentifier":"s:9CoreUIKit18BaseCollectionViewC7dequeue_3forxSgxm_10Foundation9IndexPathVtSo012UICollectionE4CellCRbzlF0L4TypeL_xmfp"},{"kind":"text","text":".Type, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CellType","preciseIdentifier":"s:9CoreUIKit18BaseCollectionViewC7dequeue_3forxSgxm_10Foundation9IndexPathVtSo012UICollectionE4CellCRbzlF0L4TypeL_xmfp"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Dequeues reusable registered cell type"}],"identifier":"doc:\/\/com.example.CoreUIKit\/documentation\/CoreUIKit\/BaseCollectionView\/dequeue(_:for:)","kind":"symbol","type":"topic","url":"\/documentation\/coreuikit\/basecollectionview\/dequeue(_:for:)"},"doc://com.example.CoreUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.example.CoreUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.example.CoreUIKit\/objc(pl)UIAppearanceContainer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BaseCollectionView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BaseCollectionView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BaseCollectionView"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.example.CoreUIKit\/objc(cs)UICollectionView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseCollectionView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseCollectionView\/title","value":"BaseCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.example.CoreUIKit~1documentation~1CoreUIKit~1BaseCollectionView\/fragments","value":[{"kind":"identifier","text":"BaseCollectionView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}